# Generated by Django 5.1.6 on 2025-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odpro', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(blank=True, max_length=250, verbose_name='Sub-Category'),
        ),
    ]
