# Generated by Django 5.1.6 on 2025-02-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odpro', '0003_alter_subcategory_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='multianswer',
            field=models.BooleanField(default=False, help_text='If yes, the question has more than one correct answer.', verbose_name='Multiple Correct Answers'),
        ),
    ]
